### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by shkolnick-kun** [shkolnick-kun/stvd-sdcc#1]
Cast @spth!

Hi, Philipp!

I think that it would be interesting to add support of sdcc to st-toolset.
The idea is to write a wrapper for sdcc to translate Cosmic or Raisonance command line to sdcc calls.
This will probably add full sdcc support to stvd as at least Raisonance gives .elf output, which I think is used by their gdb version.

Are you interested in such thing?

**Comment by spth** [comment]
While I'd consider SDCC support in STVD useful to many users, I personally don't use Windows much (in the last few months I only used it to do the compiler comparison at http://colecovision.eu/stm8/compilers.shtml).
However, Peter Dons Tychsen (donpedro2 at Sourceforge) might be interested. He did most of the work on ELF output support in SDCC for STM8. And his stated goal was to make STVD integration easier.

Philipp

**Comment by shkolnick-kun** [comment]
This issue may be closed.
